site_name: Documentation Programming Quotes [thomas-hater]

nav:
  - Home: index.md
  - User's Guide: 
      - Features: features/features.md
      - Core Functions: features/functions.md
      - User Interface: features/user-interface.md
  - Logs:
      - Initiateur: logs/log-initiateur.md
      - Contributeur 1: logs/log-contributor-1.md
      - Contributeur 2: logs/log-contributeur-2.md
      - Contributeur 3: logs/log-contributor-3.md

theme: readthedocs

